version: "2"
linters:
  default: none
  enable:
    - bodyclose
    - dogsled
    - errcheck
    - goconst
    - gocritic
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - staticcheck
    - unconvert
    - unused
    - whitespace
  settings:
    errcheck:
      check-type-assertions: true
    goconst:
      min-occurrences: 5
    gocritic:
      disabled-checks:
        - whyNoLint
        - emptyStringTest
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    lll:
      line-length: 120
    misspell:
      locale: US
    nolintlint:
      require-specific: true
      allow-unused: false
    prealloc:
      for-loops: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - path: _test\.go
        linters:
          - goconst
      - linters:
          - goconst
        text: "string `windows` has"
      - path: internal/api/
        linters:
          - revive
        text: "var-naming: avoid meaningless package names"
    paths:
      - vendor
      - third_party$
      - builtin$
      - examples$
      - legacy
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/upsun/cli
  exclusions:
    generated: lax
    paths:
      - vendor
      - third_party$
      - builtin$
      - examples$
      - legacy
