# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
project_name: platform

before:
  hooks:
    - go generate ./...
    - bash scripts/generate_completions.sh

builds:
  - binary: platform
    id: platform
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X "github.com/platformsh/cli/internal/legacy.PHPVersion={{.Env.PHP_VERSION}}"
      - -X "github.com/platformsh/cli/internal/legacy.PSHVersion={{.Env.PSH_VERSION}}"
      - -X "github.com/platformsh/cli/commands.version={{.Version}}"
      - -X "github.com/platformsh/cli/commands.commit={{.Commit}}"
      - -X "github.com/platformsh/cli/commands.date={{.Date}}"
      - -X "github.com/platformsh/cli/commands.builtBy=goreleaser"
    main: ./cmd/platform
  - binary: platform
    id: platform-macos
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X "github.com/platformsh/cli/internal/legacy.PHPVersion={{.Env.PHP_VERSION}}"
      - -X "github.com/platformsh/cli/internal/legacy.PSHVersion={{.Env.PSH_VERSION}}"
      - -X "github.com/platformsh/cli/commands.version={{.Version}}"
      - -X "github.com/platformsh/cli/commands.commit={{.Commit}}"
      - -X "github.com/platformsh/cli/commands.date={{.Date}}"
      - -X "github.com/platformsh/cli/commands.builtBy=goreleaser"
    main: ./cmd/platform

checksum:
  name_template: checksums.txt

snapshot:
  name_template: "{{ incpatch .Version }}-{{ .Commit }}-next"

changelog:
  sort: asc
  use: github-native

universal_binaries:
  - id: platform-macos
    name_template: "{{ .ProjectName }}"
    replace: true

release:
  github:
    owner: platformsh
    name: cli
  footer: |
    * * *
    **Legacy CLI release Notes**: https://github.com/platformsh/legacy-cli/releases/v{{ .Tag }}
    **Full Legacy CLI changelog**: https://github.com/platformsh/legacy-cli/compare/v{{ .PreviousTag }}...v{{ .Tag }}
    * * *
    ## Upgrade

    Upgrade using the same tool you used for installing the CLI:

    ### HomeBrew

    ```console
    brew update && brew upgrade platformsh/tap/platformsh-cli
    ```

    ### Scoop

    ```console
    scoop update platform
    ```

    ### Bash installer

    ```console
    curl -fsSL https://raw.githubusercontent.com/platformsh/cli/main/installer.sh | bash
    ```

archives:
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - completion/*
    format_overrides:
      - goos: windows
        format: zip
    rlcp: true

brews:
  - name: platformsh-cli
    tap:
      owner: platformsh
      name: homebrew-tap
      token: "{{ .Env.GITHUB_TOKEN }}"

    goarm: "7"
    folder: Formula

    commit_author:
      name: Antonis Kalipetis
      email: antonis.kalipetis@platform.sh

    homepage: https://docs.platform.sh/administration/cli.html
    description: Platform.sh CLI
    license: MIT

    dependencies:
      - name: git
        type: optional

    install: |
      bin.install "platform"
      generate_completions_from_executable(bin/"platform", "completion", shells: [:bash, :zsh])

    test: |
      system "#{bin}/platform --version"

scoops:
  - bucket:
      owner: platformsh
      name: homebrew-tap
      token: "{{ .Env.GITHUB_TOKEN }}"

    folder: Scoops
    commit_author:
      name: Antonis Kalipetis
      email: antonis.kalipetis@platform.sh

    homepage: https://docs.platform.sh/administration/cli.html
    description: Platform.sh CLI
    license: MIT

nfpms:
  - homepage: https://docs.platform.sh/administration/cli.html
    package_name: platformsh-cli
    description: Platform.sh CLI
    maintainer: Antonis Kalipetis <antonis.kalipetis@platform.sh>
    license: MIT
    vendor: Platform.sh
    builds:
      - platform
    formats:
      - apk
      - deb
      - rpm
    contents:
      - src: completion/bash/platform.bash
        dst: /etc/bash_completion.d/platform
      - src: completion/zsh/_platform
        dst: /usr/local/share/zsh/site-functions/_platform
