package commands

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"

	"github.com/fatih/color"
	"github.com/spf13/cobra"
	"github.com/symfony-cli/terminal"
	"gopkg.in/yaml.v3"

	"github.com/platformsh/cli/internal/config"
	"github.com/platformsh/cli/internal/config/alt"
)

var configInstallCommand = &cobra.Command{
	Use:   "config:install [flags] [url]",
	Short: "Installs an alternative CLI, downloading new configuration from a URL",
	Args:  cobra.ExactArgs(1),
	RunE:  runConfigInstall,
}

func runConfigInstall(cmd *cobra.Command, args []string) error {
	cmd.PrintErrln("Downloading and validating new CLI configuration...")
	cmd.PrintErrln()

	urlStr := args[0]
	if !strings.Contains(urlStr, "://") {
		urlStr = "https://" + urlStr
	}
	newCnfNode, newCnfStruct, err := alt.FetchConfig(cmd.Context(), urlStr)
	if err != nil {
		return err
	}
	cnf := config.FromContext(cmd.Context())
	newExecutable := newCnfStruct.Application.Executable
	if newExecutable == cnf.Application.Executable {
		return fmt.Errorf("cannot install config for same executable name as this program: %s", newExecutable)
	}

	// Find the directory and file paths.
	executableDir, err := alt.FindBinDir()
	if err != nil {
		return err
	}
	configDir, err := alt.FindConfigDir()
	if err != nil {
		return err
	}
	configFilePath := filepath.Join(configDir, newExecutable+".yaml")
	executableFilePath := filepath.Join(executableDir, newExecutable)

	if path, err := exec.LookPath(newExecutable); err == nil && path != executableFilePath {
		return fmt.Errorf(
			"cannot install config: an executable with the same name already exists at another location: %s",
			path,
		)
	}

	// Make a formatter to replace the home directory with ~ in filenames.
	replaceHomeDir := func() func(string) string {
		hd, err := os.UserHomeDir()
		return func(p string) string {
			if err == nil && strings.HasPrefix(p, hd) {
				return "~" + strings.TrimPrefix(p, hd)
			}
			return p
		}
	}()

	cmd.PrintErrln("The following files will be created or overwritten:")
	cmd.PrintErrf("  Config file: %s\n", color.CyanString(replaceHomeDir(configFilePath)))
	cmd.PrintErrf("  Executable: %s\n", color.CyanString(replaceHomeDir(executableFilePath)))
	if terminal.Stdin.IsInteractive() {
		if !terminal.AskConfirmation("Are you sure you want to continue?", true) {
			os.Exit(1)
		}
	}
	cmd.PrintErrln()

	// Generate the file content.
	executableContent := fmt.Sprintf(
		"#!/bin/sh\n"+
			"# This file is automatically generated by the %s.\n"+
			"export CLI_CONFIG_FILE=%s\n"+
			`[ "$#" -gt 1 ] && shift # Skip first argument`+"\n"+
			`%s "$@"`+"\n",
		cnf.Application.Name,
		configFilePath,
		cnf.Application.Executable,
	)
	configContent, err := yaml.Marshal(newCnfNode)
	if err != nil {
		return fmt.Errorf("failed to marshal new config: %w", err)
	}

	// Start writing the files.
	if err := os.MkdirAll(configDir, 0o755); err != nil {
		return err
	}
	if err := os.MkdirAll(executableDir, 0o755); err != nil {
		return err
	}
	if err := os.WriteFile(configFilePath, configContent, 0o600); err != nil {
		return err
	}
	if err := os.WriteFile(executableFilePath, []byte(executableContent), 0o700); err != nil { //nolint:gosec
		return err
	}

	cmd.PrintErrln("The files have been saved successfully.")
	cmd.PrintErrln()

	isInPath, err := alt.InPath(executableDir)
	if err != nil {
		return fmt.Errorf("could not determine if the executable directory is in the PATH: %w", err)
	}

	envVarName := "PATH"
	if runtime.GOOS == "windows" {
		envVarName = "Path"
	}

	if isInPath {
		cmd.PrintErrln("Run the new CLI with:", color.GreenString(filepath.Base(executableFilePath)))
	} else {
		cmd.PrintErrf(
			"Add the following directory to your %s: %s\n",
			envVarName,
			color.YellowString(replaceHomeDir(executableDir)),
		)
		cmd.PrintErrln()
		cmd.PrintErrln(
			"Then you will be able to run the new CLI with:",
			color.YellowString(filepath.Base(executableFilePath)),
		)
	}

	return nil
}
